config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :categories
  devise_for :users
  resources :users
  resources :movies
  
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :movies
end

app/models/concerns/categories_helper.rb
module CategoriesHelper
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :categories
    belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :pegi)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:status)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :category_list, only: [:create, :new, :edit]
  before_action :location_list, only: [:create, :new, :edit]
  before_action :authenticate_user!

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    @categories_all = Category.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show

  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def category_list
      @categories = Category.all
    end
  
  private
  def location_list
    @locations = Location.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :duration, :resume, :user_id, :category_ids, :location_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    
    def index
        @users = User.all
    end
    
    def show
        @movies = @user.movies
    end
    
    def edit
    end
    
    def destroy
        @user.destroy
    end
    
    private
    def set_user
        @user = User.find(params[:id])
    end
    
    def users_params
        params.require(:user).permit(:email, :password)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
    
end

app/helpers/movies_helper.rb
module MoviesHelper
    def movie_categorie_label(categories)
        raw categories.map { |cat| "<span>#{cat.name}</span>"}.join(', ')
    end
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :pegi %>
    <%= form.number_field :pegi %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pegi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.pegi %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Pegi:</strong>
  <%= @category.pegi %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h1> Welcome to Cinestar Land ! <h1>

app/views/layouts/_navigation.html.erb
<header>
    <nav>
        <%= link_to 'Accueil', root_path  %>
        <%= link_to 'Tous les films', movies_path %>
        <% if user_signed_in? %>
            <% if current_user.user_type == 'admin' %>
                <%= link_to 'Categories', categories_path %>
                <%= link_to 'Location', locations_path %>
            <% end %>
        <% end %>
        <% if user_signed_in? %>
        <%= current_user.email %>
            <%= link_to 'Mes films', user_path(current_user) %>
            <%= link_to 'Deconnexion', destroy_user_session_path, method: :delete%>  
        <% else %>
            <%= link_to 'Connexion', new_user_session_path %>
            <%= link_to 'Inscription', new_user_registration_path %>
        <% end %>
        
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.status %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @location.status %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.time_select :duration %>
  </div>

  <div class="field">
    <%= form.label :resume %>
    <%= form.text_area :resume %>
  </div>

  <div class="field">
    <%= form.label :categorie %>
    <%= form.collection_select :category_ids, @categories, :id, :name, prompt: true %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.collection_select :location_status, @locations, :id, :status, prompt: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Duration</th>
      <th>Resume</th>
      <th>Statut location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.duration %></td>
        <td><%= movie.resume %></td>
        <td><%= movie.location_status %></td>
        <td><%= link_to 'Show', movie %></td>
        <% if movie.user == current_user %>
          <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
          <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% if current_user.user_type == 'admin' %>
          <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
          <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @movie.duration %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @movie.resume %>
</p>

<p>
  <strong>Statut de la location:</strong>
  <%= @movie.location_status %>
</p>

<% if @movie.user == current_user or current_user.user_type == 'admin' %>
  <%= link_to 'Edit', edit_movie_path(@movie) %>
<% end %>  |
<%= link_to 'Back', movies_path %>

app/views/users/show.html.erb
<h1> Bonjour <%= @user.email %><h1>

<ul>
    <% @movies.each do |movie| %>
    <li>
        <%= link_to movie.title, movie_path(movie) %>
    </li>
    <% end %>
</ul>